name: oraeapp
description: Hapo Toy Project ORAE

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.2.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Font-M
      fonts:
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
    - family: Font-B
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 500