name: oraeapp
description: Hapo Toy Project ORAE

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.2.3
  intl: ^0.16.1
  http: ^0.12.0+4
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/resources/

  fonts:
    - family: Font-M
      fonts:
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
    - family: Font-B
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 500